// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "YOUR_API_KEY_HERE",
    authDomain: "fatakse-flutter-mvp.firebaseapp.com",
    projectId: "fatakse-flutter-mvp",
    storageBucket: "fatakse-flutter-mvp.firebasestorage.app",
    messagingSenderId: "534945286343",
    appId: "1:534945286343:web:5f0c02ff5192d6ecabd6e2",
    measurementId: "G-HH0NCQ9Q2P",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "YOUR_API_KEY_HERE",
    appId: "1:534945286343:android:6ff9a2075a85ab69abd6e2",
    messagingSenderId: "534945286343",
    projectId: "fatakse-flutter-mvp",
    storageBucket: "fatakse-flutter-mvp.firebasestorage.app",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "YOUR_API_KEY_HERE",
    appId: "1:534945286343:ios:6ff9a2075a85ab69abd6e2",
    messagingSenderId: "534945286343",
    projectId: "fatakse-flutter-mvp",
    storageBucket: "fatakse-flutter-mvp.firebasestorage.app",
    iosBundleId: "com.example.stageLinkMvp",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "YOUR_API_KEY_HERE",
    authDomain: "fatakse-flutter-mvp.firebaseapp.com",
    projectId: "fatakse-flutter-mvp",
    storageBucket: "fatakse-flutter-mvp.firebasestorage.app",
    messagingSenderId: "534945286343",
    appId: "1:534945286343:web:5f0c02ff5192d6ecabd6e2",
    measurementId: "G-HH0NCQ9Q2P",
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "YOUR_API_KEY_HERE",
    authDomain: "fatakse-flutter-mvp.firebaseapp.com",
    projectId: "fatakse-flutter-mvp",
    storageBucket: "fatakse-flutter-mvp.firebasestorage.app",
    messagingSenderId: "534945286343",
    appId: "1:534945286343:web:5f0c02ff5192d6ecabd6e2",
    measurementId: "G-HH0NCQ9Q2P",
  );
}
