// Mocks generated by Mockito 5.4.5 from annotations
// in fatakse_prod/test/mocks/mock_services.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:fatakse_prod/core/services/error_service.dart' as _i5;
import 'package:fatakse_prod/core/services/logger_service.dart' as _i7;
import 'package:fatakse_prod/core/services/performance_service.dart' as _i6;
import 'package:fatakse_prod/core/services/security_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeException_0 extends _i1.SmartFake implements Exception {
  _FakeException_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_1 extends _i1.SmartFake implements Duration {
  _FakeDuration_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_2<T1> extends _i1.SmartFake implements _i2.Future<T1> {
  _FakeFuture_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SecurityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecurityService extends _i1.Mock implements _i3.SecurityService {
  MockSecurityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String hashPassword(
    String? password,
    String? salt,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #hashPassword,
          [
            password,
            salt,
          ],
        ),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #hashPassword,
            [
              password,
              salt,
            ],
          ),
        ),
      ) as String);

  @override
  String generateSalt() => (super.noSuchMethod(
        Invocation.method(
          #generateSalt,
          [],
        ),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #generateSalt,
            [],
          ),
        ),
      ) as String);

  @override
  bool isValidEmail(String? email) => (super.noSuchMethod(
        Invocation.method(
          #isValidEmail,
          [email],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isValidPhoneNumber(String? phone) => (super.noSuchMethod(
        Invocation.method(
          #isValidPhoneNumber,
          [phone],
        ),
        returnValue: false,
      ) as bool);

  @override
  String sanitizeInput(String? input) => (super.noSuchMethod(
        Invocation.method(
          #sanitizeInput,
          [input],
        ),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #sanitizeInput,
            [input],
          ),
        ),
      ) as String);

  @override
  bool isStrongPassword(String? password) => (super.noSuchMethod(
        Invocation.method(
          #isStrongPassword,
          [password],
        ),
        returnValue: false,
      ) as bool);

  @override
  String generateApiKey() => (super.noSuchMethod(
        Invocation.method(
          #generateApiKey,
          [],
        ),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #generateApiKey,
            [],
          ),
        ),
      ) as String);

  @override
  bool isValidJWT(String? token) => (super.noSuchMethod(
        Invocation.method(
          #isValidJWT,
          [token],
        ),
        returnValue: false,
      ) as bool);

  @override
  void logSecurityEvent(
    String? event,
    Map<String, dynamic>? details,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #logSecurityEvent,
          [
            event,
            details,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool checkRateLimit(
    String? identifier,
    int? maxRequests,
    Duration? window,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkRateLimit,
          [
            identifier,
            maxRequests,
            window,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  String encryptData(String? data) => (super.noSuchMethod(
        Invocation.method(
          #encryptData,
          [data],
        ),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #encryptData,
            [data],
          ),
        ),
      ) as String);

  @override
  String decryptData(String? encryptedData) => (super.noSuchMethod(
        Invocation.method(
          #decryptData,
          [encryptedData],
        ),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #decryptData,
            [encryptedData],
          ),
        ),
      ) as String);
}

/// A class which mocks [ErrorService].
///
/// See the documentation for Mockito's code generation for more information.
class MockErrorService extends _i1.Mock implements _i5.ErrorService {
  MockErrorService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void logError(
    dynamic error,
    StackTrace? stackTrace, {
    Map<String, Object>? context,
    String? userId,
    String? feature,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #logError,
          [
            error,
            stackTrace,
          ],
          {
            #context: context,
            #userId: userId,
            #feature: feature,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logUserAction(
    String? action,
    String? userId, {
    Map<String, Object>? properties,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #logUserAction,
          [
            action,
            userId,
          ],
          {#properties: properties},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logPerformance(
    String? operation,
    Duration? duration, {
    Map<String, Object>? metadata,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #logPerformance,
          [
            operation,
            duration,
          ],
          {#metadata: metadata},
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getNetworkErrorMessage(dynamic error) => (super.noSuchMethod(
        Invocation.method(
          #getNetworkErrorMessage,
          [error],
        ),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #getNetworkErrorMessage,
            [error],
          ),
        ),
      ) as String);

  @override
  String getAuthErrorMessage(String? errorCode) => (super.noSuchMethod(
        Invocation.method(
          #getAuthErrorMessage,
          [errorCode],
        ),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #getAuthErrorMessage,
            [errorCode],
          ),
        ),
      ) as String);

  @override
  Exception createBusinessException(
    String? message, {
    String? code,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBusinessException,
          [message],
          {#code: code},
        ),
        returnValue: _FakeException_0(
          this,
          Invocation.method(
            #createBusinessException,
            [message],
            {#code: code},
          ),
        ),
      ) as Exception);
}

/// A class which mocks [PerformanceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPerformanceService extends _i1.Mock
    implements _i6.PerformanceService {
  MockPerformanceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void startOperation(String? operationName) => super.noSuchMethod(
        Invocation.method(
          #startOperation,
          [operationName],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Duration endOperation(String? operationName) => (super.noSuchMethod(
        Invocation.method(
          #endOperation,
          [operationName],
        ),
        returnValue: _FakeDuration_1(
          this,
          Invocation.method(
            #endOperation,
            [operationName],
          ),
        ),
      ) as Duration);

  @override
  _i2.Future<T> timeAsyncOperation<T>(
    String? operationName,
    _i2.Future<T> Function()? operation,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #timeAsyncOperation,
          [
            operationName,
            operation,
          ],
        ),
        returnValue: _i4.ifNotNull(
              _i4.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #timeAsyncOperation,
                  [
                    operationName,
                    operation,
                  ],
                ),
              ),
              (T v) => _i2.Future<T>.value(v),
            ) ??
            _FakeFuture_2<T>(
              this,
              Invocation.method(
                #timeAsyncOperation,
                [
                  operationName,
                  operation,
                ],
              ),
            ),
      ) as _i2.Future<T>);

  @override
  T timeOperation<T>(
    String? operationName,
    T Function()? operation,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #timeOperation,
          [
            operationName,
            operation,
          ],
        ),
        returnValue: _i4.dummyValue<T>(
          this,
          Invocation.method(
            #timeOperation,
            [
              operationName,
              operation,
            ],
          ),
        ),
      ) as T);

  @override
  Duration getAveragePerformance(String? operationName) => (super.noSuchMethod(
        Invocation.method(
          #getAveragePerformance,
          [operationName],
        ),
        returnValue: _FakeDuration_1(
          this,
          Invocation.method(
            #getAveragePerformance,
            [operationName],
          ),
        ),
      ) as Duration);

  @override
  Map<String, dynamic> getPerformanceStats() => (super.noSuchMethod(
        Invocation.method(
          #getPerformanceStats,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void monitorMemory() => super.noSuchMethod(
        Invocation.method(
          #monitorMemory,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void trackAppStartup() => super.noSuchMethod(
        Invocation.method(
          #trackAppStartup,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearHistory() => super.noSuchMethod(
        Invocation.method(
          #clearHistory,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Stream<Map<String, dynamic>> getPerformanceStream() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPerformanceStream,
          [],
        ),
        returnValue: _i2.Stream<Map<String, dynamic>>.empty(),
      ) as _i2.Stream<Map<String, dynamic>>);
}

/// A class which mocks [LoggerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoggerService extends _i1.Mock implements _i7.LoggerService {
  MockLoggerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  void debug(
    String? message, {
    String? feature,
    Map<String, dynamic>? metadata,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #debug,
          [message],
          {
            #feature: feature,
            #metadata: metadata,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void info(
    String? message, {
    String? feature,
    Map<String, dynamic>? metadata,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #info,
          [message],
          {
            #feature: feature,
            #metadata: metadata,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void warning(
    String? message, {
    String? feature,
    Map<String, dynamic>? metadata,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #warning,
          [message],
          {
            #feature: feature,
            #metadata: metadata,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void error(
    String? message, {
    String? feature,
    Map<String, dynamic>? metadata,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #error,
          [message],
          {
            #feature: feature,
            #metadata: metadata,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void critical(
    String? message, {
    String? feature,
    Map<String, dynamic>? metadata,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #critical,
          [message],
          {
            #feature: feature,
            #metadata: metadata,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i7.LogEntry> getRecentLogs({
    int? limit = 100,
    _i7.LogLevel? minLevel,
    String? feature,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentLogs,
          [],
          {
            #limit: limit,
            #minLevel: minLevel,
            #feature: feature,
          },
        ),
        returnValue: <_i7.LogEntry>[],
      ) as List<_i7.LogEntry>);

  @override
  List<_i7.LogEntry> getLogsByDateRange(
    DateTime? start,
    DateTime? end, {
    _i7.LogLevel? minLevel,
    String? feature,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLogsByDateRange,
          [
            start,
            end,
          ],
          {
            #minLevel: minLevel,
            #feature: feature,
          },
        ),
        returnValue: <_i7.LogEntry>[],
      ) as List<_i7.LogEntry>);

  @override
  Map<String, dynamic> getLogStats() => (super.noSuchMethod(
        Invocation.method(
          #getLogStats,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void clearLogs() => super.noSuchMethod(
        Invocation.method(
          #clearLogs,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
